INSERT INTO public.users (password, role, username) VALUES ('$2a$10$fVSt47y2WVngJfNkW2UWCuwQHLnSq93mGlmYo0WaQFT0Ic8AiT6Z2', 'ADMIN', 'admin');
INSERT INTO public.users (password, role, username) VALUES ('$2a$10$4ggnMboUpPD7wS0f0YvH6uLCwEuGBxWvxZO01rJBOch3L5Ws8PaIC', 'USER', 'sidorova');
INSERT INTO public.users (password, role, username) VALUES ('$2a$10$CxT14AdmA0Fz5iBq3S6dgOPz/amDpkacgJO01unK1nrxqNMpbTxFu', 'USER', 'petrova');
INSERT INTO public.users (password, role, username) VALUES ('$2a$10$HRCjd2nIHk9IG2dvsQvAM.oYugaIgbabezeVGwBx8SAuYolfofZDq', 'USER', 'testov');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (12, 'Дружелюбная и активная порода', 'https://example.com/images/labrador.jpg', 'Лабрадор ретривер', 'Канада', 'LARGE', 'Дружелюбный, активный, умный');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (14, 'Крошечная, но смелая собака-компаньон', 'https://example.com/images/chihuahua.jpg', 'Чихуахуа', 'Мексика', 'TOY', 'Смелый, независимый, живой');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (11, 'Умная, преданная, хорошо обучаемая', 'https://example.com/images/german_shepherd.jpg', 'Немецкая овчарка', 'Германия', 'LARGE', 'Умный, преданный, защитный');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (13, 'Любопытная и добрая порода', 'https://example.com/images/beagle.jpg', 'Бигль', 'Англия', 'MEDIUM', 'Дружелюбный, любопытный, ласковый');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (8, 'Добродушный гигант с мягким характером', 'https://example.com/images/great_dane.jpg', 'Дог', 'Германия', 'GIANT', 'Спокойный, любящий, уравновешенный');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (15, 'Энергичная и элегантная порода', 'https://example.com/images/yorkshire_terrier.jpg', 'Йоркширский терьер', 'Англия', 'TOY', 'Бдительный, решительный, ласковый');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (13, 'Пушистая, умная и преданная собака', 'https://example.com/images/spitz.jpg', 'Шпиц', 'Германия', 'SMALL', 'Бдительный, энергичный, любящий');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (10, 'Легко обучаемая порода с крепким телосложением', 'https://example.com/images/boxer.jpg', 'Боксер', 'Германия', 'MEDIUM', 'Игривый, преданный, уверенный');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (10, 'Выносливая, преданная ездовая собака', 'https://example.com/images/siberian_husky.jpg', 'Сибирский хаски', 'Россия', 'MEDIUM', 'Дружелюбный, энергичный, независимый');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (12, 'Нежная и интеллигентная собака-компаньон', 'https://example.com/images/poodle.jpg', 'Пудель', 'Франция', 'MEDIUM', 'Интеллигентный, активный, послушный');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (11, 'Сильная и отважная порода', 'https://example.com/images/rottweiler.jpg', 'Ротвейлер', 'Германия', 'LARGE', 'Защитный, уверенный, преданный');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (14, 'Преданная и терпеливая, хороша для семьи', 'https://example.com/images/golden_retriever.jpg', 'Золотистый ретривер', 'Шотландия', 'LARGE', 'Дружелюбный, терпеливый, мягкий');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (9, 'Храбрая и энергичная порода', 'https://example.com/images/doberman.jpg', 'Доберман', 'Германия', 'LARGE', 'Бдительный, энергичный, решительный');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (15, 'Компактная и живой охотник', 'https://example.com/images/jack_russell.jpg', 'Джек-рассел-терьер', 'Англия', 'SMALL', 'Игривый, живой, смелый');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (12, 'Красивая, спокойная и независимая', 'https://example.com/images/akita.jpg', 'Акита', 'Япония', 'LARGE', 'Достойный, независимый, преданный');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (13, 'Игривый и сообразительный, подходит для квартир', 'https://example.com/images/papillon.jpg', 'Папильон', 'Франция', 'TOY', 'Умный, живой, ласковый');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (13, 'Компактная сторожевая собака', 'https://example.com/images/shih_tzu.jpg', 'Ши-тцу', 'Китай', 'TOY', 'Спокойный, ласковый, упрямый');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (14, 'Длинношерстная охотничья собака', 'https://example.com/images/cocker_spaniel.jpg', 'Кокер-спаниель', 'Англия', 'MEDIUM', 'Энергичный, веселый, ласковый');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (11, 'Устойчивый к холоду, хороший охранник', 'https://example.com/images/alaskan_malamute.jpg', 'Аляскинский маламут', 'США', 'LARGE', 'Независимый, дружелюбный, упрямый');
INSERT INTO public.breeds (avg_lifespan_years, description, image_url, name, origin_country, size, temperament) VALUES (13, 'Сильная и умная порода с короткой шерстью', 'https://example.com/images/pitbull.jpg', 'Американский питбуль', 'США', 'MEDIUM', 'Энергичный, умный, уверенный');
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2018-03-12', 'Серый', 'MALE', 'Лаки', 57.8, 10, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2016-09-15', 'Рыжий', 'MALE', 'Шарик', 48.3, 13, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2022-11-29', 'Пестрый', 'FEMALE', 'Дружок', 49.8, 14, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2022-09-18', 'Серый', 'FEMALE', 'Бим', 30.2, 15, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2025-01-05', 'Черный', 'MALE', 'Луна', 42.4, 11, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2015-01-06', 'Белый', 'MALE', 'Буч', 6.7, 19, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2017-12-28', 'Серый', 'FEMALE', 'Чара', 7.5, 12, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2024-12-06', 'Коричневый', 'MALE', 'Буч', 46.2, 20, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2021-11-03', 'Пестрый', 'FEMALE', 'Лайма', 53.7, 17, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2021-11-19', 'Черный', 'MALE', 'Дружок', 37.5, 4, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2021-05-18', 'Рыжий', 'FEMALE', 'Шарик', 45.6, 12, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2015-08-15', 'Коричневый', 'MALE', 'Лайма', 45.9, 9, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2023-06-17', 'Пестрый', 'MALE', 'Бим', 21, 14, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2015-02-11', 'Черный', 'FEMALE', 'Тайсон', 50.6, 3, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2022-02-18', 'Рыжий', 'MALE', 'Шарик', 6.3, 13, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2019-01-12', 'Белый', 'MALE', 'Лаки', 52.7, 16, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2017-11-29', 'Черный', 'FEMALE', 'Бим', 15, 7, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2023-10-01', 'Пестрый', 'MALE', 'Чара', 51.3, 16, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2016-01-31', 'Коричневый', 'FEMALE', 'Снежок', 22.8, 5, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2022-04-09', 'Палевый', 'MALE', 'Чара', 37, 18, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2021-05-19', 'Черный', 'MALE', 'Лаки', 48, 1, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2024-09-10', 'Палевый', 'FEMALE', 'Бим', 55.8, 10, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2017-12-17', 'Пестрый', 'FEMALE', 'Гром', 50.8, 9, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2014-07-27', 'Пестрый', 'FEMALE', 'Гром', 43.6, 15, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2016-11-16', 'Черный', 'MALE', 'Buddy', 37, 6, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2014-10-30', 'Рыжий', 'FEMALE', 'Тоша', 47.6, 19, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2016-11-16', 'Белый', 'FEMALE', 'Шарик', 19.5, 2, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2021-09-20', 'Белый', 'MALE', 'Буся', 8, 18, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2016-11-16', 'Черный', 'MALE', 'Атос', 37, 20, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2019-11-29', 'Черный', 'MALE', 'Грей', 58.8, 11, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2017-08-09', 'Рыжий', 'FEMALE', 'Марта', 51.9, 8, 3);
INSERT INTO public.dogs (birth_date, color, gender, name, weight_kg, breed_id, owner_id) VALUES ('2023-04-27', 'Коричневый', 'FEMALE', 'Чара', 52.4, 17, 3);
